# Generated by Django 5.1.4 on 2025-01-09 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "finger_id",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(3),
                            django.core.validators.RegexValidator(
                                "^\\d+$", message="FINGER ID must be numeric."
                            ),
                        ],
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ingener", "Ingener"),
                            ("Call operator", "Call operator"),
                            ("CEO", "CEO"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Passive", "Passive")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChechingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checking_status",
                    models.CharField(
                        choices=[("Came", "Came"), ("Gone", "Gone")], max_length=7
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time",
                        to="models.usermodel",
                    ),
                ),
            ],
        ),
    ]
