# Generated by Django 5.1.4 on 2025-01-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ingener", "Ingener"),
                    ("Call operator", "Call operator"),
                    ("CEO", "CEO"),
                ],
                default="Ingener",
                max_length=255,
                null=True,
            ),
        ),
    ]
