# Generated by Django 5.1.4 on 2025-01-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_alter_usermodel_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Passive", "Passive")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
